"""bf16-vs-NF4 geometry comparison (quantization-artifact rebuttal).

Reviewer worry: the hourglass (mid-network silhouette dip while probe stays
high) might be amplified by 4-bit NF4 quantization. We re-extracted the
memory banks in full bf16 (subset, n=80/lang) and recompute the per-layer
4-way linear-probe accuracy + silhouette, comparing to the NF4 banks
subsampled to the SAME first-80 sentences. If both show the hourglass, it is
not a quantization artifact.

  uv run --with torch --with numpy --with scikit-learn \
         python code/compare_bf16_geometry.py

Writes the steer-layer / dip numbers and a tex macro file
paper/latell/bf16_stats.tex.
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import torch
from sklearn.decomposition import PCA
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import silhouette_score
from sklearn.model_selection import cross_val_score
from sklearn.preprocessing import StandardScaler

ROOT = Path(__file__).resolve().parent.parent
LANGS = ["hin", "mai", "npi", "bho"]
STEER_L = 20  # Llama


def load_bank(model, limit=None):
    mats, labels = [], []
    for li, lg in enumerate(LANGS):
        p = torch.load(ROOT / "results" / "memory_banks" / model / f"{lg}.pt",
                       map_location="cpu", weights_only=False)
        v = p["vectors"].float().numpy()             # (N, L+1, H)
        if limit is not None:
            v = v[:limit]
        mats.append(v)
        labels.append(np.full(v.shape[0], li))
    X = np.concatenate(mats, axis=0)
    y = np.concatenate(labels)
    return np.transpose(X, (1, 0, 2)), y             # (L+1, M, H), (M,)


def curve(Xl, y):
    nL = Xl.shape[0]
    probe, sil = [], []
    for l in range(nL):
        Z = StandardScaler().fit_transform(Xl[l])
        Z = PCA(n_components=min(50, Z.shape[0] - 1, Z.shape[1]),
                random_state=0).fit_transform(Z)
        acc = cross_val_score(LogisticRegression(max_iter=2000, C=1.0),
                              Z, y, cv=5, scoring="accuracy").mean()
        probe.append(acc)
        sil.append(silhouette_score(Z, y))
    return np.array(probe), np.array(sil)


def main():
    # NF4 banks subsampled to the same first-80 sentences as the bf16 subset.
    Xn, yn = load_bank("llama", limit=80)
    Xb, yb = load_bank("llama_bf16")
    print(f"nf4 subset {Xn.shape}, bf16 {Xb.shape}")

    pn, sn = curve(Xn, yn)
    pb, sb = curve(Xb, yb)

    def describe(tag, p, s):
        print(f"\n[{tag}] probe: mean={p.mean():.3f}, @L{STEER_L}={p[STEER_L]:.3f}; "
              f"silhouette: min={s.min():.3f}@L{s.argmin()}, "
              f"@L{STEER_L}={s[STEER_L]:.3f}, max={s.max():.3f}@L{s.argmax()}")
        # hourglass = sil dips in a mid band then recovers toward output
        mid = s[8:21].min()
        early, late = s[1], s[-1]
        print(f"        hourglass check: early L1={early:.2f}, mid-min={mid:.2f}, "
              f"final={late:.2f}  ({'DIP+RECOVER' if mid < early and mid < late else 'no clear hourglass'})")
        return mid
    midn = describe("NF4", pn, sn)
    midb = describe("bf16", pb, sb)

    # correlation of the two silhouette curves (shape agreement)
    r = float(np.corrcoef(sn, sb)[0, 1])
    print(f"\nsilhouette-curve correlation NF4 vs bf16: r = {r:.3f}")

    tex = [
        "% AUTO-GENERATED by code/compare_bf16_geometry.py",
        f"\\newcommand{{\\bfprobeL}}{{{pb[STEER_L]:.2f}}}",
        f"\\newcommand{{\\bfsilmin}}{{{sb.min():.2f}}}",
        f"\\newcommand{{\\bfsilcorr}}{{{r:.3f}}}",
        f"\\newcommand{{\\nfsilmin}}{{{sn.min():.2f}}}",
    ]
    (ROOT / "paper" / "latell" / "bf16_stats.tex").write_text("\n".join(tex) + "\n")
    print("wrote paper/latell/bf16_stats.tex")


if __name__ == "__main__":
    main()
