"""Convergent validity: do the reference-free automatic metrics agree with the
3-judge panel, per generation? Merges the panel parquet (panel_mean__* judge scores)
with the robust-metrics parquet (sem_labse, indicbert_ppl, cmi, ...) on `id` and
reports Spearman rank correlations (robust to the heavy-tailed perplexity).

If the panel and independent automatic metrics correlate in the expected directions,
the two validate each other with no human or judge assumption shared.

Writes macros to paper/mlj/convergent_stats.tex.

    .venv/bin/python code/convergent_validity.py
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import spearmanr

ROOT = Path(__file__).resolve().parent.parent
PANEL = ROOT / "results" / "judge_panel"
MET = ROOT / "results" / "robust_metrics"
TEX = ROOT / "paper" / "mlj" / "convergent_stats.tex"

# (panel judge dimension, automatic metric, expected sign, macro tag)
PAIRS = [
    ("fluency",            "indicbert_ppl", "-", "fluppl"),   # native-LM PPL vs judge fluency
    ("language_adherence", "cmi",           "+", "adhcmi"),   # code-mixing vs judge adherence
    ("language_adherence", "sem_labse",     "-", "adhsem"),   # meaning drift as adherence rises
    ("fluency",            "rep_rate",      "-", "flurep"),   # repetition vs fluency
    ("fluency",            "distinct2",     "+", "fludist"),  # diversity vs fluency
    ("coherence",          "rep_rate",      "-", "cohrep"),   # repetition vs coherence
]


def load_merged(model):
    p = pd.read_parquet(PANEL / f"{model}_finer30_panel.parquet")
    m = pd.read_parquet(MET / f"{model}_finer30_metrics.parquet")
    pcols = ["id"] + [c for c in p.columns if c.startswith("panel_mean__")]
    df = p[pcols].merge(m, on="id", how="inner")
    return df


def main():
    dfs = {m: load_merged(m) for m in ["llama", "aya"]}
    pool = pd.concat(dfs.values(), ignore_index=True)

    macros = {}
    print(f"{'dimension ~ metric':34} {'llama':>8} {'aya':>8} {'pooled':>8}")
    print("-" * 62)
    for dim, met, sign, tag in PAIRS:
        jc = f"panel_mean__{dim}"
        rhos = {}
        for name, df in [("llama", dfs["llama"]), ("aya", dfs["aya"]), ("pooled", pool)]:
            if jc not in df.columns or met not in df.columns:
                rhos[name] = float("nan")
                continue
            x = pd.to_numeric(df[jc], errors="coerce")
            y = pd.to_numeric(df[met], errors="coerce")
            ok = x.notna() & y.notna()
            rhos[name] = spearmanr(x[ok], y[ok]).statistic if ok.sum() > 5 else float("nan")
        print(f"{dim+' ~ '+met:34} {rhos['llama']:>8.2f} {rhos['aya']:>8.2f} "
              f"{rhos['pooled']:>8.2f}   (expect {sign})")
        macros[f"cv{tag}"] = f"{rhos['pooled']:.2f}"
        macros[f"cv{tag}llama"] = f"{rhos['llama']:.2f}"

    TEX.parent.mkdir(parents=True, exist_ok=True)
    lines = ["% AUTO-GENERATED by code/convergent_validity.py -- do not edit by hand.",
             f"% Spearman rho, panel judge score vs reference-free metric. n={len(pool)} pooled."]
    lines += [rf"\newcommand{{\{k}}}{{{v}}}" for k, v in macros.items()]
    TEX.write_text("\n".join(lines) + "\n")
    print(f"\nwrote {TEX}  ({len(macros)} macros; pooled n={len(pool)})")


if __name__ == "__main__":
    main()
