"""Judge-composition robustness test for the multi-LLM panel.

Addresses the concern that a 3-judge panel with two Google seats
(gemini-3.1-pro + gemini-3.5-flash) and one OpenAI seat (gpt-5.5) might let the
Google reading dominate the headline. Rather than buy a third family, we SHOW the
qualitative conclusions are invariant to judge composition by recomputing the
headline peak-adherence under five weightings:

    full            equal mean of all three judges
    -gemini_pro     leave-one-out (mean of the other two)
    -gpt            leave-one-out
    -gemini_flash   leave-one-out
    family_balanced average the two Google seats first, then average with GPT
                    (so Google and OpenAI families get equal weight -> neutralises
                     the 2:1 seat count)

Two claims must hold under EVERY weighting for the paper's story to be
composition-independent:
    (C1) Nepali is Llama's most steerable target (peak_npi > peak_mai, peak_bho).
    (C2) Llama-Nepali's peak exceeds Aya's best peak (the cross-model gap).

Writes robustness macros to paper/mlj/judge_sensitivity.tex.

    .venv/bin/python code/judge_sensitivity.py
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
PANEL = ROOT / "results" / "judge_panel"
TEX_OUT = ROOT / "paper" / "mlj" / "judge_sensitivity.tex"
DIM = "language_adherence"
JUD = ["gemini_pro", "gpt", "gemini_flash"]
TL = {"npi": "Nepali", "mai": "Maithili", "bho": "Bhojpuri"}

WEIGHTS = {
    "full":            lambda d: d[JUD].mean(axis=1),
    "-gemini_pro":     lambda d: d[["gpt", "gemini_flash"]].mean(axis=1),
    "-gpt":            lambda d: d[["gemini_pro", "gemini_flash"]].mean(axis=1),
    "-gemini_flash":   lambda d: d[["gemini_pro", "gpt"]].mean(axis=1),
    "family_balanced": lambda d: 0.5 * d[["gemini_pro", "gemini_flash"]].mean(axis=1)
                                 + 0.5 * d["gpt"],
}


def load(model):
    f = PANEL / f"{model}_finer30_panel.parquet"
    df = pd.read_parquet(f)
    cols = {j: pd.to_numeric(df[f"{j}__{DIM}"], errors="coerce") for j in JUD}
    out = df[["target_lang", "alpha"]].copy()
    for j in JUD:
        out[j] = cols[j]
    return out


def peak_by_target(df, wfun):
    """Per target, max over alpha of the cell-mean weighted score."""
    df = df.copy()
    df["s"] = wfun(df)
    peaks = {}
    for t in TL:
        g = df[df.target_lang == t].groupby("alpha")["s"].mean()
        peaks[t] = float(g.max())
    return peaks


def main():
    llama, aya = load("llama"), load("aya")
    print(f"{'weighting':16} | " + "  ".join(f"L-{TL[t][:3]}" for t in TL)
          + " | " + "  ".join(f"A-{TL[t][:3]}" for t in TL)
          + " | C1 C2")
    print("-" * 78)
    c1_all, c2_all = [], []
    npi_peaks = []
    for name, wfun in WEIGHTS.items():
        lp = peak_by_target(llama, wfun)
        ap = peak_by_target(aya, wfun)
        c1 = lp["npi"] > lp["mai"] and lp["npi"] > lp["bho"]      # Nepali top on Llama
        c2 = lp["npi"] > max(ap.values())                         # Llama-npi > Aya best
        c1_all.append(c1); c2_all.append(c2); npi_peaks.append(lp["npi"])
        print(f"{name:16} | "
              + "  ".join(f"{lp[t]:4.2f}" for t in TL) + " | "
              + "  ".join(f"{ap[t]:4.2f}" for t in TL) + " | "
              + f"{'Y' if c1 else 'N'}  {'Y' if c2 else 'N'}")
    print("-" * 78)
    print(f"C1 (Nepali most steerable on Llama) holds under ALL weightings: {all(c1_all)}")
    print(f"C2 (Llama-Nepali > Aya best) holds under ALL weightings:        {all(c2_all)}")
    print(f"Llama-Nepali peak ranges [{min(npi_peaks):.2f}, {max(npi_peaks):.2f}] across weightings")

    TEX_OUT.parent.mkdir(parents=True, exist_ok=True)
    macros = {
        "npipeaklo": f"{min(npi_peaks):.2f}",
        "npipeakhi": f"{max(npi_peaks):.2f}",
        "robustCone": "holds" if all(c1_all) else "fails",
        "robustCtwo": "holds" if all(c2_all) else "fails",
    }
    lines = ["% AUTO-GENERATED by code/judge_sensitivity.py -- do not edit by hand.",
             "% Judge-composition robustness (leave-one-out + family-balanced)."]
    lines += [rf"\newcommand{{\{k}}}{{{v}}}" for k, v in macros.items()]
    TEX_OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {TEX_OUT}")


if __name__ == "__main__":
    main()
