"""Emit the steered-generation examples table (paper/latell/examples_table.tex).

Native-Devanagari outputs (wrapped in \\deva{...}); the document is built with
XeLaTeX + a Devanagari font (Noto Sans Devanagari on Overleaf). Shows one prompt
per target traced across alpha so the adherence-fluency trade-off is visible:
control (Hindi) -> readable code-switch -> high-adherence-but-broken.

  uv run --with pandas --with pyarrow python code/make_examples_table.py
"""
from __future__ import annotations

from pathlib import Path

import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "results" / "generations" / "llama_all_l20_finer30_scored.parquet"
OUT = ROOT / "paper" / "latell" / "examples_table.tex"
TLAB = {"npi": "Nepali", "mai": "Maithili", "bho": "Bhojpuri"}

# (target, eval_id, [alphas], short English gloss of the Hindi prompt)
SEL = [
    ("npi", "eval_0002", [0.0, -1.0, -2.0],
     "Why and how is Pongal celebrated in South India?"),
    ("mai", "eval_0020", [0.0, -2.5],
     "Briefly introduce the major forms of Indian classical music."),
    ("bho", "eval_0025", [0.0, -2.5],
     "How does Bhangra dance represent Punjabi culture?"),
]


def esc(s: str) -> str:
    """Escape the few TeX-special ASCII chars; leave Devanagari untouched."""
    for a, b in [("&", r"\&"), ("%", r"\%"), ("#", r"\#"),
                 ("_", r"\_"), ("$", r"\$")]:
        s = s.replace(a, b)
    return s


def deva(s: str, n: int = 14) -> str:
    """First n whitespace tokens of the Devanagari string, wrapped for XeLaTeX."""
    t = " ".join(str(s).split()[:n]).replace("|", "।")
    return r"\deva{" + esc(t) + r"}"


def main():
    df = pd.read_parquet(SRC)
    for c in ["language_adherence", "fluency"]:
        df[c] = pd.to_numeric(df[c], errors="coerce")

    lines = [
        r"% AUTO-GENERATED by code/make_examples_table.py -- do not edit by hand.",
        r"% Native Devanagari: build with XeLaTeX (\deva = a Devanagari font).",
        r"\begin{table*}[tp]\centering\footnotesize",
        r"\setlength{\tabcolsep}{5pt}",
        r"\caption{Steered generations (Llama, single-layer L20), first 14 tokens of "
        r"each output. Each block is one prompt traced across the steering coefficient "
        r"$\alpha$ ($\alpha{=}0$ is the unsteered Hindi control). Adh/Flu are the "
        r"LLM-judge language-adherence and fluency scores (1--5). The trade-off is "
        r"explicit: at the adherence peak ($\alpha{=}-2.0$, Nepali) the text is "
        r"target-language but degenerates into a repetition loop (fluency~1); the "
        r"readable shift sits at smaller $|\alpha|$.}",
        r"\label{tab:examples}",
        r"\begin{tabular}{@{}r cc l@{}}",
        r"\toprule",
        r"$\alpha$ & Adh & Flu & Generation (first 14 tokens, Devanagari) \\",
    ]
    for t, eid, alphas, gloss in SEL:
        sub = df[(df.target_lang == t) & (df.eval_id == eid)]
        prompt = sub.iloc[0].prompt
        lines.append(r"\midrule")
        lines.append(
            r"\multicolumn{4}{@{}p{0.95\textwidth}}{\textbf{" + TLAB[t] +
            r"} target. Prompt: " + deva(prompt, 40) +
            r"~\textit{(" + esc(gloss) + r")}} \\[2pt]")
        for a in alphas:
            r = sub[sub.alpha == a].iloc[0]
            tag = r"\,{\scriptsize(ctrl)}" if a == 0.0 else ""
            adh, flu = int(r.language_adherence), int(r.fluency)
            lines.append(
                f"${a:+.1f}${tag} & {adh} & {flu} & {deva(r.generation)} \\\\")
    lines += [r"\bottomrule", r"\end{tabular}", r"\end{table*}", ""]
    OUT.write_text("\n".join(lines))
    print("wrote", OUT)


if __name__ == "__main__":
    main()
