"""Aggregate robust_metrics output into the paper's control-vs-peak story + macros.

Reads results/robust_metrics/*_metrics.parquet and, per target language, contrasts the
alpha=0 Hindi control with the adherence-peak alpha on each automatic metric:

  semantic preservation (sem_labse)   : does meaning survive the language shift?
  fluency floor (indicbert_ppl)        : native-LM pseudo-perplexity (lower=better)
  degeneracy (distinct2, rep_rate, self_bleu)
  code-mixing (cmi, m_index, i_index)

Writes LaTeX macros to paper/mlj/robust_stats.tex.

    .venv/bin/python code/robust_metrics_stats.py
"""
from __future__ import annotations

from pathlib import Path

import numpy as np
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
MET = ROOT / "results" / "robust_metrics"
PANEL = ROOT / "results" / "judge_panel"
TEX = ROOT / "paper" / "mlj" / "robust_stats.tex"
TL = {"npi": "npi", "mai": "mai", "bho": "bho"}


def peak_alphas(model):
    """Adherence-peak alpha per target from the panel parquet (keeps metrics aligned
    with the reported adherence peak, which differs Llama vs Aya)."""
    f = PANEL / f"{model}_finer30_panel.parquet"
    if not f.exists():
        return {"npi": -2.0, "mai": -2.5, "bho": -3.0}
    df = pd.read_parquet(f)
    out = {}
    for t in TL:
        g = df[df.target_lang == t].groupby("alpha")["panel_mean__language_adherence"].mean()
        out[t] = float(g.idxmax()) if len(g) else 0.0
    return out
METRICS = ["sem_labse", "sem_enc2", "indicbert_ppl",
           "distinct2", "rep_rate", "self_bleu", "cmi", "m_index", "i_index"]


def num(s):
    return pd.to_numeric(s, errors="coerce")


def main():
    files = sorted(MET.glob("*_metrics.parquet"))
    if not files:
        raise SystemExit(f"no *_metrics.parquet in {MET}")
    macros = {}
    for f in files:
        model = f.stem.split("_")[0]                       # llama / aya
        df = pd.read_parquet(f)
        have = [m for m in METRICS if m in df.columns]
        PEAK = peak_alphas(model)
        print(f"\n=== {f.name}  (metrics: {have}; peak alphas {PEAK}) ===")
        for t, pk in PEAK.items():
            sub = df[df.target_lang == t]
            if sub.empty:
                continue
            ctrl = sub[sub.alpha == 0.0]
            peak = sub[sub.alpha == pk]
            row = [f"{TL[t]:4}"]
            for m in have:
                # PPL is exp(mean neg-log-lik); a few garbage tokens blow up the mean,
                # so report the robust MEDIAN for perplexity, mean for the rest.
                agg = (lambda s: num(s).median()) if m == "indicbert_ppl" else (lambda s: num(s).mean())
                cv = agg(ctrl[m])
                pv = agg(peak[m])
                row.append(f"{m}={cv:.2f}->{pv:.2f}")
                tag = f"{model}{t}"
                short = {"sem_labse": "semlabse", "sem_enc2": "semenc",
                         "indicbert_ppl": "ppl", "distinct2": "dist",
                         "rep_rate": "rep", "self_bleu": "sbleu",
                         "cmi": "cmi", "m_index": "mindex", "i_index": "iindex"}[m]
                macros[f"{short}{tag}ctrl"] = f"{cv:.2f}"
                macros[f"{short}{tag}peak"] = f"{pv:.2f}"
            print("  " + "  ".join(row))

    TEX.parent.mkdir(parents=True, exist_ok=True)
    lines = ["% AUTO-GENERATED by code/robust_metrics_stats.py -- do not edit by hand.",
             "% Reference-free automatic metrics: control (alpha=0) -> adherence peak."]
    lines += [rf"\newcommand{{\{k}}}{{{v}}}" for k, v in macros.items()]
    TEX.write_text("\n".join(lines) + "\n")
    print(f"\nwrote {TEX}  ({len(macros)} macros)")


if __name__ == "__main__":
    main()
