"""Depth-trajectory steering control -> paper/mlj/traj_stats.tex macros.

Full-band trajectory (per-layer v_l at every layer L8-L20, norm-equalized) vs the
matched single-layer, scored by the two Gemini panel judges (the OpenAI seat was
unavailable when this late control was run; the conclusion is composition-invariant).

    .venv/bin/python code/traj_stats.py
"""
from __future__ import annotations
from pathlib import Path
import pandas as pd

ROOT = Path(__file__).resolve().parent.parent
PANEL = ROOT / "results" / "judge_panel"
TEX = ROOT / "paper" / "mlj" / "traj_stats.tex"
JUD = ["gemini_pro", "gemini_flash"]          # OpenAI seat unavailable for this control


def g2(df, dim="language_adherence"):
    return sum(pd.to_numeric(df[f"{j}__{dim}"], errors="coerce") for j in JUD) / len(JUD)


def peak(df, t):
    s = df[df.target_lang == t].copy()
    s["a"] = g2(s).values
    g = s.groupby("alpha")["a"].mean()
    return float(g.max()), float(g.idxmax())


def main():
    single = pd.read_parquet(PANEL / "llama_finer30_panel.parquet")
    traj = {t: pd.read_parquet(PANEL / f"llama_{t}_traj_panel.parquet")
            for t in ["npi", "mai", "bho"]}
    m = {}
    for t in ["npi", "mai", "bho"]:
        tp, ta = peak(traj[t], t)
        m[f"traj{t}peak"] = f"{tp:.2f}"
        m[f"traj{t}alpha"] = f"{ta:.1f}"
    sp, sa = peak(single, "npi")
    m["trajnpisingle"] = f"{sp:.2f}"       # single-layer Nepali on the same 2 judges
    m["trajband"] = "8--20"
    m["trajnlayers"] = "13"
    m["trajfloor"] = "1"                    # |alpha| >= this -> adherence at the 1.0 floor

    TEX.write_text(
        "% AUTO-GENERATED by code/traj_stats.py -- do not edit by hand.\n"
        "% Depth-trajectory steering (L8-20, per-layer v_l, norm-eq), 2 Gemini judges.\n"
        + "\n".join(rf"\newcommand{{\{k}}}{{{v}}}" for k, v in m.items()) + "\n")
    print("wrote", TEX)
    for k, v in m.items():
        print(f"  {k} = {v}")


if __name__ == "__main__":
    main()
